
public class Camera extends Machine {
	//generated by using option 'Add unimplemented methods'
	@Override
	public void start() {
		System.out.println("Camera started");
	}

	@Override
	public void doStuff() {
		System.out.println("Camera doing stuff");
		
	}

	@Override
	public void shutDown() {
		System.out.println("Camera shutting down");
	}
}
