
public class Car extends Machine {
	
	//generated by using option 'Add unimplemented methods'
	@Override
	public void start() {
		System.out.println("Car started");
	}

	@Override
	public void doStuff() {
		System.out.println("Doing stuff in car");
		
	}

	@Override
	public void shutDown() {
		System.out.println("Shutting down car.");
		
	}
}
